name: Nexus Data Pipeline
on:
  schedule:
    - cron: '13 11 * * *'   # 08:13 BRT (Fura a fila das 08h)
    - cron: '27 17 * * *'   # 14:17 BRT (Fura a fila das 14h)
    - cron: '33 19 * * *'   # 16:33 BRT (Fura a fila das 16h30)
  workflow_dispatch:        # Permite rodar manualmente

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # Atualizado de v3 para v4
      - uses: actions/checkout@v4 
      
      # Atualizado de v4 para v5
      - name: Setup Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
          
      - name: Install Libs
        run: pip install pandas supabase python-dotenv aiohttp openpyxl
        
      - name: Run ETL
        env:
          GOBI_TOKEN: ${{ secrets.GOBI_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python update_supabase.py
